### ISSUE TITLE
flutter open whatsapp does not work with Android 11

### ISSUE THREAD

**Issue by alexisuranga** [rohit1814/flutter_open_whatsapp#20]
Greetings I have an app that has worked perfectly up to android 10, with andoid 11 it does not open whatsApp and it does not show me any error it simply does not do anything, there is something special or some permission that I must give in android 11.

first of all, Thanks

**Comment by MJahangir82** [comment]
I have the same issue. @alexisuranga have you fixed it ?

**Comment by alexisuranga** [comment]
Greetings I was able to solve with the following code,
I had not tried.

**Tested on Android 11**

`import 'dart:io';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  void _contactViaWhatsApp(context) async {
    String whatsAppUrl = "";
    String phoneNumber = '+584245206539';
    String description = "Coloca tu mensaje Aqui";
    if (Platform.isIOS) {
      whatsAppUrl =
      'whatsapp://wa.me/$phoneNumber/?text=${Uri.parse(description)}';
    } else {
      whatsAppUrl =
      'https://wa.me/+$phoneNumber?text=${Uri.parse(description)}';
    }
     await launch(whatsAppUrl);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Enviar Mensajes a WhatsApp'),
        ),
        body: Center(
            child: TextButton(
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  const Text(
                    "Open Whatsapp in Android 11",
                  ),
                ],
              ),
              onPressed: () {
                _contactViaWhatsApp(context);
              },
            )),
      ),
    );
  }
}`
